#!/usr/bin/env node
/**
 * Regenerate src/data/recorded-run.json from a live Mergit deployment.
 *
 * The landing page replays a real completed run. Rather than hand-maintaining that data (and
 * risking it drifting into fiction), this script reads it straight from the API:
 *
 *   node scripts/record-run.mjs > src/data/recorded-run.json
 *   node scripts/record-run.mjs --base http://localhost:8000 --goal <goal_id>
 *
 * Pacing is the one authored part: recorded runs finish faster than a person can read them, so
 * each task is given a readable slot on a fixed timeline. Everything else is verbatim.
 */

const args = process.argv.slice(2);
const argOf = (flag, fallback) => {
  const i = args.indexOf(flag);
  return i === -1 ? fallback : args[i + 1];
};

const BASE = (argOf("--base", "https://mergit.onrender.com") || "").replace(/\/$/, "");
const WANTED_GOAL = argOf("--goal", null);
const LOOP_SECONDS = Number(argOf("--loop", "16"));

async function getJson(path) {
  const res = await fetch(`${BASE}${path}`);
  if (!res.ok) throw new Error(`GET ${path} → ${res.status} ${await res.text()}`);
  return res.json();
}

function summarise(output) {
  if (!output || typeof output !== "object") return "Completed.";
  if (typeof output.pr_url === "string") {
    const n = output.pr_url.split("/").pop();
    return `Pull request opened — Mergit-proto #${n}.`;
  }
  if (typeof output.summary === "string") {
    const points = Array.isArray(output.key_points) ? output.key_points.join(", ") : "";
    return points ? `${output.summary} — ${points}.` : `${output.summary}.`;
  }
  if (typeof output.text === "string") return `${output.text}.`;
  return "Completed.";
}

/** Give each task an evenly spaced, readable slot: run, settle, then mint its proof. */
function pace(count, loop) {
  const first = 2.8;
  const tail = 2.8; // room after the last proof for the COMPLETED beat
  const per = (loop - first - tail) / count;
  return Array.from({ length: count }, (_, i) => {
    const startAt = +(first + i * per).toFixed(1);
    return {
      startAt,
      doneAt: +(startAt + per * 0.56).toFixed(1),
      proofAt: +(startAt + per * 0.73).toFixed(1),
    };
  });
}

const { goals } = await getJson("/api/goals");
const completed = goals.filter((g) => g.status === "COMPLETED");
if (!completed.length) throw new Error("no COMPLETED goal to record");

const chosen = WANTED_GOAL
  ? completed.find((g) => g.goal_id === WANTED_GOAL)
  : completed.sort((a, b) => b.updated_at - a.updated_at)[0];
if (!chosen) throw new Error(`goal ${WANTED_GOAL} not found or not COMPLETED`);

const detail = await getJson(`/api/goals/${chosen.goal_id}`);
const proofs = await getJson("/api/economy/proofs?limit=200");
const chain = await getJson("/api/economy/chain/status");

const tasks = (detail.tasks || []).filter((t) => t.status === "DONE");
if (!tasks.length) throw new Error("recorded goal has no completed tasks");

const timings = pace(tasks.length, LOOP_SECONDS);
const byTask = new Map(proofs.map((p) => [p.task_id, p]));

const recorded = {
  _comment:
    "Generated by scripts/record-run.mjs from a live deployment. Do not hand-edit — regenerate instead.",
  source: BASE,
  goal_id: detail.goal_id,
  title: detail.title,
  chain: {
    name: chain.name,
    chainId: chain.chainId,
    proofOfWork: chain.contracts?.ProofOfWork ?? null,
  },
  tasks: tasks.map((t, i) => {
    const proof = byTask.get(t.id);
    return {
      id: t.id,
      role: t.agent_name,
      description: t.description,
      summary: summarise(t.output),
      resultHash: proof?.result_hash ?? null,
      blockNumber: proof?.block_number ?? null,
      ...timings[i],
    };
  }),
  result: summarise(tasks[tasks.length - 1].output).replace(/\.$/, "").replace("Mergit-proto", "mergit-io/Mergit-proto"),
  loopSeconds: LOOP_SECONDS,
  pacing: "authored",
};

process.stdout.write(`${JSON.stringify(recorded, null, 2)}\n`);
