import { useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { RUN_STAGES } from "../components/landing/runStages";

/* The landing page.
   ------------------------------------------------------------------------------
   A fork of ThreeUI's "Kage" (MIT) with Mergit's copy throughout, generated by
   frontend/scripts/build-kage-landing.mjs from a pinned upstream commit. The
   whole page — five sections, its own scroll, a live WebGL scene and a wordmark
   the scene draws in 3D — is one authored document, so it is framed rather than
   ported: any attempt to re-implement it in React would be a redrawing of it, and
   the point of choosing it was that it already looks like this.

   `sandbox="allow-scripts"` and no same-origin: the page needs to run and needs
   nothing of ours. Its two calls to action reach the console by asking the parent
   to route, which is what the message handler below is for. */
const PAGE_URL = "/landing/kage/index.html";

export function KageLanding() {
  const frameRef = useRef<HTMLIFrameElement>(null);
  const navigate = useNavigate();

  useEffect(() => {
    document.documentElement.dataset.landing = "kage";
    return () => {
      delete document.documentElement.dataset.landing;
    };
  }, []);

  useEffect(() => {
    const onMessage = (event: MessageEvent) => {
      /* From our frame only, and only ever an internal path. Without the second
         check a crafted message could route the visitor anywhere, which is an
         open redirect wearing a navigation event's clothes. */
      if (event.source !== frameRef.current?.contentWindow) return;
      const data = event.data as { kind?: string; to?: string } | null;
      if (!data || data.kind !== "mergit:navigate") return;
      const to = data.to;
      if (typeof to !== "string" || !to.startsWith("/") || to.startsWith("//")) return;
      navigate(to);
    };
    window.addEventListener("message", onMessage);
    return () => window.removeEventListener("message", onMessage);
  }, [navigate]);

  return (
    <div className="kage-host">
      <iframe
        ref={frameRef}
        title="Mergit — describe the outcome, not the steps"
        src={PAGE_URL}
        sandbox="allow-scripts"
        loading="eager"
      />

      {/* The page's argument, in this document rather than inside the frame.
          Nothing framed is visible to a crawler or reachable by a screen reader,
          and the landing page is the one page where that matters most. */}
      <div className="sr-only">
        <h1>Mergit — describe the outcome. Not the steps.</h1>
        <p>
          One sentence becomes a task graph. Specialised agents execute it with real tools —
          reading repositories, running code, opening pull requests — and every finished task
          hashes its output and mints a proof on chain.
        </p>
        <h2>The run</h2>
        <ol>
          {RUN_STAGES.map((stage) => (
            <li key={stage.title}>
              <h3>{stage.title}</h3>
              <p>{stage.body}</p>
              <p>{`Produces: ${stage.out}`}</p>
            </li>
          ))}
        </ol>
        <h2>Proof of work</h2>
        <p>
          Agents assert that they did the work. Mergit hashes what they produced and writes it to
          an EVM chain, so the claim can be checked by anyone rather than trusted.
        </p>
        <p>
          <a href="/app">Open the console</a>
        </p>
      </div>
    </div>
  );
}
